-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 17:29:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shopexpress
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopexpress
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopexpress` DEFAULT CHARACTER SET utf8mb3 ;
USE `shopexpress` ;

-- -----------------------------------------------------
-- Table `shopexpress`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopexpress`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(300) NULL DEFAULT NULL,
  `role` ENUM('seller', 'buyer', 'admin') NULL DEFAULT NULL,
  `address` VARCHAR(300) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shopexpress`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopexpress`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sellerId` INT NOT NULL,
  `buyerId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `buyerId` (`buyerId` ASC) INVISIBLE,
  INDEX `sellerId` (`sellerId` ASC) VISIBLE,
  CONSTRAINT `carts_buyerId`
    FOREIGN KEY (`buyerId`)
    REFERENCES `shopexpress`.`users` (`id`),
  CONSTRAINT `carts_sellerId`
    FOREIGN KEY (`sellerId`)
    REFERENCES `shopexpress`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shopexpress`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopexpress`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` ENUM('Fashion', 'Home', 'Beauty', 'Books', 'Electronic', 'Baby') NULL DEFAULT NULL,
  `sellerId` INT NOT NULL,
  `productCode` VARCHAR(45) NOT NULL,
  `productName` VARCHAR(45) NOT NULL,
  `productDesc` VARCHAR(500) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `stockNum` INT NULL DEFAULT NULL,
  `imageUrl` VARCHAR(200) NULL DEFAULT NULL,
  `available` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `itemCode_UNIQUE` (`productCode` ASC) INVISIBLE,
  INDEX `sellerId` (`sellerId` ASC) INVISIBLE,
  CONSTRAINT `products_sellerId`
    FOREIGN KEY (`sellerId`)
    REFERENCES `shopexpress`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shopexpress`.`cartitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopexpress`.`cartitems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cartId` INT NOT NULL,
  `productId` INT NOT NULL,
  `productCode` VARCHAR(45) NULL DEFAULT NULL,
  `productName` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cartId` (`cartId` ASC) INVISIBLE,
  INDEX `productId` (`productId` ASC) VISIBLE,
  CONSTRAINT `cartItems_cartId`
    FOREIGN KEY (`cartId`)
    REFERENCES `shopexpress`.`carts` (`id`),
  CONSTRAINT `cartItems_productId`
    FOREIGN KEY (`productId`)
    REFERENCES `shopexpress`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shopexpress`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopexpress`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `data` MEDIUMBLOB NOT NULL,
  `mimeType` VARCHAR(45) NOT NULL,
  `productId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `productId_UNIQUE` (`productId` ASC) VISIBLE,
  INDEX `productId` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_images_productId`
    FOREIGN KEY (`productId`)
    REFERENCES `shopexpress`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shopexpress`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopexpress`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sellerId` INT NOT NULL,
  `buyerId` INT NOT NULL,
  `status` ENUM('unSubmitted', 'BuyerConfirmed', 'Paid', 'SellerConfirmed', 'Transporting', 'Received', 'Canceled') NOT NULL DEFAULT 'unSubmitted',
  `orderTime` DATETIME NULL DEFAULT NULL,
  `paymentInfo` VARCHAR(45) NULL DEFAULT NULL,
  `totalPrice` DECIMAL(10,2) NULL DEFAULT NULL,
  `taxes` DECIMAL(10,2) NULL DEFAULT NULL,
  `shippingFee` DECIMAL(10,2) NULL DEFAULT NULL,
  `finalTotalPay` DECIMAL(10,2) NULL DEFAULT NULL,
  `deliveryInfo` VARCHAR(400) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `buyerId` (`buyerId` ASC) INVISIBLE,
  INDEX `sellerId` (`sellerId` ASC) VISIBLE,
  CONSTRAINT `orders_buyerId`
    FOREIGN KEY (`buyerId`)
    REFERENCES `shopexpress`.`users` (`id`),
  CONSTRAINT `orders_sellerId`
    FOREIGN KEY (`sellerId`)
    REFERENCES `shopexpress`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `shopexpress`.`orderitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopexpress`.`orderitems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT NOT NULL,
  `productId` INT NOT NULL,
  `productCode` VARCHAR(45) NULL DEFAULT NULL,
  `productName` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `orderId` (`orderId` ASC) INVISIBLE,
  INDEX `productId` (`productId` ASC) VISIBLE,
  CONSTRAINT `orderItems_orderId`
    FOREIGN KEY (`orderId`)
    REFERENCES `shopexpress`.`orders` (`id`),
  CONSTRAINT `orderItems_productId`
    FOREIGN KEY (`productId`)
    REFERENCES `shopexpress`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
